[package]
name = "hline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grep = "0.2"
thiserror = "1"
termion = "1"
clap = "2.33"

[dev-dependencies]
test-case = "1.2.1"
stringreader = "0.1"
